#!/usr/bin/env python
# -*- coding: utf-8 -*-

dlib_errors={
"/home/vector/Documents/Проект/Брови/Домиком/1.jpg",
"/home/vector/Documents/Проект/Брови/Домиком/6pBSWfFebRU.jpg",
"/home/vector/Documents/Проект/Брови/Домиком/17_449160.jpg", 
"/home/vector/Documents/340x464_0xd42ee42a_10290128931424358864.jpeg",
"/home/vector/Documents/Проект/Брови/Домиком/36918962_2521241227901897_7814025260801458176_n.jpg", 
"/home/vector/Documents/Проект/Брови/Домиком/JQaJYKXtS_4.jpg",
"/home/vector/Documents/Проект/Брови/Домиком/nd4sOTfSV3c.jpg",
"/home/vector/Documents/Проект/Брови/Домиком/OmUdqyA0ws4.jpg",
"/home/vector/Documents/Проект/Брови/Домиком/orig55646.jpg",
"/home/vector/Documents/Проект/Брови/Домиком/Безымянный98.jpg",

"/home/vector/Documents/Проект/Брови/Полукруглые/A1-XpqQqQVc.jpg", 
"/home/vector/Documents/Проект/Брови/Полукруглые/AObuUTGszQE.jpg",
"/home/vector/Documents/Проект/Брови/Полукруглые/ddVbD8qYTIg.jpg",
"/home/vector/Documents/Проект/Брови/Полукруглые/oOgL8cyeyHM.jpg",
"/home/vector/Documents/Проект/Брови/Полукруглые/sCZcHN3z6TI.jpg",
"/home/vector/Documents/Проект/Брови/Полукруглые/TqQ6o8pLgB4.jpg",
"/home/vector/Documents/Проект/Брови/Полукруглые/ZbKUp-VdZXs.jpg", 

"/home/vector/Documents/Проект/Брови/Прямые1FfuiiCEfgo.jpg",
"/home/vector/Documents/Проект/Брови/Прямые/1FfuiiCEfgo.jpg",
"/home/vector/Documents/Проект/Брови/Прямые/6J1JnDQgGEA.jpg",
"/home/vector/Documents/Проект/Брови/Прямые/A6dk9dQydI4.jpg",
"/home/vector/Documents/Проект/Брови/Прямые/ERh_YQ7s2RM.jpg", 
"/home/vector/Documents/Проект/Брови/Прямые/EYWNg8SsLQQ.jpg", 
"/home/vector/Documents/Проект/Брови/Прямые/_h7wfNz3B44.jpg",
"/home/vector/Documents/Проект/Брови/Прямые/opQB-0nkwqM.jpg",
"/home/vector/Documents/Проект/Брови/Прямые/VfLcVpREPJA.jpg",
"/home/vector/Documents/Проект/Брови/Прямые/xflqsbqJeuk.jpg",

"/home/vector/Documents/Проект/Брови/Светлые редкие/-99xgPDCtO8.jpg", 
"/home/vector/Documents/Проект/Брови/Светлые редкие/4zPdSU4hskM.jpg", 
"/home/vector/Documents/Проект/Брови/Светлые редкие/aGYhqRQ95VE.jpg",
"/home/vector/Documents/Проект/Брови/Светлые редкие/b44M059EVvM.jpg",
"/home/vector/Documents/Проект/Брови/Светлые редкие/HqU_x1p4Crc.jpg",
"/home/vector/Documents/Проект/Брови/Светлые редкие/LFBfACdUa0Q.jpg",
"/home/vector/Documents/Проект/Брови/Светлые редкие/lPk-viB6CUY.jpg",
"/home/vector/Documents/Проект/Брови/Светлые редкие/moKFHbZqD-I.jpg",

"/home/vector/Documents/Проект/Брови/С подъемом/0ZN2t5dntmE.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/1qfl2CR5sfk.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/2M60jdnNJP8.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/3dQWpz_RqSg.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/HVFmT23QktE.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/j9ZWI4shJnk.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/onL2ilSIg5w.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/PtVEJ_03jwM.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/TFA-4boN-2Q.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/uLTkZhDauBU.jpg",
"/home/vector/Documents/Проект/Брови/С подъемом/xWBzBOBWF_8.jpg",

"/home/vector/Documents/Проект/Брови/Сросшиеся/0_16f7e4_c03ae75a_orig.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/8_unibrow_08_webmixerdetailed_jpg.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/271_img2.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/2017-07-07_11-45-42.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/10074.unibrow.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/5613136c68da49d84fd36dbd39c22ac3.jpeg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/47582558_273284136613954_4124557195641156784_n.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/blog-dirks.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/c13e083c3b2a1150a3cced05b09b7aed.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/Mashia-Andzhim-Deya.jpg",
"/home/vector/Documents/Проект/Брови/Сросшиеся/личное-монобровь-388212.jpeg",

"/home/vector/Documents/Проект/Брови/Темные густые/1-bFZ_IWu-o.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/9aOsZlloIFE.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/40GkOWwvO5U.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/bAejmi-jSjM.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/Bciy9lEZXP0.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/Biu3p6nVHwI.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/cd4oMrOLcsc.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/FG_J4uQmiMw.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/FsZljjh41GU.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/JuKnLPQ8VGU.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/lbo0uiQoYUk.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/LuudMVTmqYY.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/mYMzVecetuw.jpg", 
"/home/vector/Documents/Проект/Брови/Темные густые/noiG9yEbCz4.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/rH28l2YDTfc.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/tqtUdpvnOFc.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/tRc3_iao-f8.jpg",
"/home/vector/Documents/Проект/Брови/Темные густые/WuHxCfLIrd4.jpg",

"/home/vector/Documents/Проект/Веки/Закрытые внутри/8i4shwUT7do.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/8yEuy_lV9O8.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/cU_-34-9pzg.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/DBWjInltkUw.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/FHctJR5udXg.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/hsXczncrhu0.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/hUAq-qZeY14.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/SgLR0bn6rkY.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/u4jhg7EdNSw.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/V_Ie4ZTC4OQ.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/ylGZt2ogBTE.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые внутри/zZAW_Tuw_aM.jpg",

"/home/vector/Documents/Проект/Веки/Закрытые посередине/0q4eyHLHC50.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/1kDaQzS4S5w.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/5POAJARg9ZQ.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/AN_nJNCsSi0.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/AWlw0G-QWDk%20(1).jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/C8JALJHIO-E.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/cgB8vZcow3U.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/CIXf6zONHF4.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/DpqSK751ic8.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/JPX7fnY24Xg.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые посередине/xcbAk5KkVvc.jpg",

"/home/vector/Documents/Проект/Веки/Закрытые снаружи/5ucZWUbE9KM.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/cLfwwph35LE.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/D3AwF--bdk8.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/Gxwk1YkBak8.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/iKai1TBOWMc.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/KNZfLChyrxc.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/lq9deBD66Io.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/QIw5PM1k2g8.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/rjFfJr1QxC0.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/uXKZpwICeIk.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/V7aZTSpLWJs.jpg",
"/home/vector/Documents/Проект/Веки/Закрытые снаружи/XZcIUuBvAEo.jpg",

"/home/vector/Documents/Проект/Глаза/Близкая посадка глаз/A9LALiHOSuU.jpg",
"/home/vector/Documents/Проект/Глаза/Близкая посадка глаз/FtKTure4.jpeg",
"/home/vector/Documents/Проект/Глаза/Близкая посадка глаз/KAF4N80DF_g.jpg",
"/home/vector/Documents/Проект/Глаза/Близкая посадка глаз/LsfkzB1A29I.jpg",
"/home/vector/Documents/Проект/Глаза/Близкая посадка глаз/MgY-U7U0P7E.jpg",
"/home/vector/Documents/Проект/Глаза/Близкая посадка глаз/VM0MjWdFIb4_preview.jpeg",

"/home/vector/Documents/Проект/Глаза/Голубые/2-34.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/2YMiJLvTaGA.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/8ZflNK7TNys.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/aFlK-_NF_zI.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/blue-eyes-boy-boyfriend-cameron-dallas-Favim.com-1830779.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/d0H5nZNFDtE.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/esaPUzlT8nI.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/f5Bq8Hy1psM.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/HHHHHHHHH.jpeg",
"/home/vector/Documents/Проект/Глаза/Голубые/kjP9Wz6h1ws.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/Nikolska-Nastia-2.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/olkMfckYBlA.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/orig%20(6).jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/SDwG3g_hSwg.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/Tkr4bl0jnaE.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/UFL0ZcgMlSI.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/WzMgsE-_Lcc.jpg",
"/home/vector/Documents/Проект/Глаза/Голубые/ребенок-с-голубыми-глазами.jpg",

"/home/vector/Documents/Проект/Глаза/Зеленые/8yqSQaLe7eM.jpg",
"/home/vector/Documents/Проект/Глаза/Зеленые/b02EufBQcb8.jpg",
"/home/vector/Documents/Проект/Глаза/Зеленые/kak_vybrat__parnja_po_cvetu_glaz.jpg",
"/home/vector/Documents/Проект/Глаза/Зеленые/oPqwiVeSxvk.jpg",
"/home/vector/Documents/Проект/Глаза/Зеленые/oPqwiVeSxvk.jpg",
"/home/vector/Documents/Проект/Глаза/Зеленые/qmjLugBkR2Y.jpg",
"/home/vector/Documents/Проект/Глаза/Зеленые/ryzhevolosaya-devushka-s-zelenymi-glazami.jpg",
"/home/vector/Documents/Проект/Глаза/Зеленые/ryzhevolosaya-devushka-s-zelenymi-glazami.jpg",

"/home/vector/Documents/Проект/Глаза/Карие и черные/IESP67gkkJQ.jpg",
"/home/vector/Documents/Проект/Глаза/Карие и черные/karie-glaza_3.jpg",
"/home/vector/Documents/Проект/Глаза/Карие и черные/ylftFlXxsEY.jpg", 

"/home/vector/Documents/Проект/Глаза/Серые/1d032843ae55d8495594e8366aa043b6--amazing-eyes-andy-black.jpg",
"/home/vector/Documents/Проект/Глаза/Серые/7a6fa2c04.jpg",
"/home/vector/Documents/Проект/Глаза/Серые/7a6fa2c04.jpg", 
"/home/vector/Documents/Проект/Глаза/Серые/AGw40eYGNP8.jpg",
"/home/vector/Documents/Проект/Глаза/Серые/depositphotos_13838396-stock-photo-blue-eyes-children-girl-relaxed.jpg",
"/home/vector/Documents/Проект/Глаза/Серые/d_yBV6rLQxg.jpg",
"/home/vector/Documents/Проект/Глаза/Серые/Fc6iujkWxO4.jpg",
"/home/vector/Documents/Проект/Глаза/Серые/Q-_lcnZNrf4.jpg",
"/home/vector/Documents/Проект/Глаза/Серые/serie-glaza-u-malishki.jpg",
"/home/vector/Documents/Проект/Глаза/Серые/XyYevLRH3XI.jpg",

"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/_2pyRjANRzs.jpg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/_7t3nbjN7m0.jpg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/7a6fa2c04_preview.jpeg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/e90188611a40d49677ee32f1bb3163e7_preview.jpeg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/gBWGBi2ZsL0.jpg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/jzfZmGs5oiE.jpg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/jA1WD6CE9Lw.jpg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/_kfqtdtXjHM_preview.jpeg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/MR77Kus1PW0.jpg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/normal_DSC_1037.jpg", 
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/normal_IMG_1054.jpg", 
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/oaaTNWJ8IuE_preview.jpeg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/pDZXzv8tE-w_preview.jpeg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/Pm1CZ4rc.jpeg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/rK6rT-6CZmU.jpg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/RXKVTgKM.jpeg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/te7-vUjOgxE.jpg",
"/home/vector/Documents/Проект/Глаза/широкая посадка глаз/YRmvaWqE0_w.jpg",

"/home/vector/Documents/Проект/Губы/Верхняя губа с галочкой/h3sZVKgG3wM.jpg",
"/home/vector/Documents/Проект/Губы/Верхняя губа с галочкой/heg_4zm3Qk8.jpg",
"/home/vector/Documents/Проект/Губы/Верхняя губа с галочкой/iN49rbO8eoA.jpg",
"/home/vector/Documents/Проект/Губы/Верхняя губа с галочкой/ircZsWhZjSg.jpg",
"/home/vector/Documents/Проект/Губы/Верхняя губа с галочкой/iTztseNuoAc.jpg",
"/home/vector/Documents/Проект/Губы/Верхняя губа с галочкой/QhIcVbM_OIU.jpg", 
"/home/vector/Documents/Проект/Губы/Верхняя губа с галочкой/Tnyr3P5iMDo.jpg",

"/home/vector/Documents/Проект/Губы/Прямая верхняя губа/dytdoRPTP_8.jpg",
"/home/vector/Documents/Проект/Губы/Прямая верхняя губа/LYWYEa8UT_Q.jpg",
"/home/vector/Documents/Проект/Губы/Прямая верхняя губа/sFhlZksJDWY.jpg",
"/home/vector/Documents/Проект/Губы/Прямая верхняя губа/ysP7EJbmFXo.jpg",
"/home/vector/Documents/Проект/Губы/Прямая верхняя губа/z_811192bb.jpg",

"/home/vector/Documents/Проект/Губы/Уголки губ вверх/4zT0ceEf2Q8.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вверх/b7248a1a39930c42aaf9ecd10291ee76.jpeg",
"/home/vector/Documents/Проект/Губы/Уголки губ вверх/cpr-f3qEyhw.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вверх/DWxyvBFE1DQ.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вверх/m_SACCwc99Q.jpg",  
"/home/vector/Documents/Проект/Губы/Уголки губ вверх/UkZBPV8-QFY%20(1).jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вверх/Vwkojpn6Hp4.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вверх/x0z62UuZGdY.jpg",

"/home/vector/Documents/Проект/Губы/Уголки губ вниз/0ZN2t5dntmE.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вниз/7WliDf0dupg.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вниз/9S9hWV-tIzA.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вниз/e5AMGgsRlLc.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вниз/fyzK5tVfhcI.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вниз/s1200.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ вниз/TQFoBAMaUHw.jpg",

"/home/vector/Documents/Проект/Губы/Уголки губ прямые/0fe0SH23h9Y.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/1QQUR68kJKM.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/9vWtfpvoSSE.jpg", 
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/CLUvohNZJSs.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/haircut-5-1-242x242.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/iN49rbO8eoA%20(1).jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/ircZsWhZjSg%20(1).jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/iTztseNuoAc%20(1).jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/Kj4z9Di-MPM.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/X93VtPhkvuM.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/XKKQSbXV1kc.jpg",
"/home/vector/Documents/Проект/Губы/Уголки губ прямые/Yqfe4Fpfdww.jpg",

"/home/vector/Documents/Проект/Губы/Узкий рот/fyzK5tVfhcI%20(1).jpg",
"/home/vector/Documents/Проект/Губы/Узкий рот/giLoShyOowM.jpg",
"/home/vector/Documents/Проект/Губы/Узкий рот/rQsggtAzomY.jpg",
"/home/vector/Documents/Проект/Губы/Узкий рот/UkZBPV8-QFY.jpg",

"/home/vector/Documents/Проект/Губы/Широкий рот/_4b_AWFsIoI.jpg",
"/home/vector/Documents/Проект/Губы/Широкий рот/119G0Id5k90.jpg",
"/home/vector/Documents/Проект/Губы/Широкий рот/a2qTVdf4JUc.jpg",
"/home/vector/Documents/Проект/Губы/Широкий рот/N16_igvX1mg.jpg",
"/home/vector/Documents/Проект/Губы/Широкий рот/qAt3Ifd8LQE.jpg",
"/home/vector/Documents/Проект/Губы/Широкий рот/QEgwtvCfgZQ.jpg",
"/home/vector/Documents/Проект/Губы/Широкий рот/TphoLMXtBJQ.jpg",
"/home/vector/Documents/Проект/Губы/Широкий рот/Wj_z4WDoSsk.jpg",


"/home/vector/Documents/Проект/Лоб/Волосы буквой М/DBWjInltkUw.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы буквой М/dlVc6zJrPsQ.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы буквой М/eANnBdO6CJk.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы буквой М/O-1rZ8Nnugw.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы буквой М/QC0QQlUNz8E.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы буквой М/roH-4WgrblA.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы буквой М/xcbAk5KkVvc.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы буквой М/Z2h3Lt4yBSI.jpg",

"/home/vector/Documents/Проект/Лоб/Волосы на лбу/4wIXi32pUrg.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы на лбу/05p8_XDGN9M.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы на лбу/8b9c1D8qIZY.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы на лбу/afq14zxv1.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы на лбу/jZ9f0jHzGyU.jpg",
"/home/vector/Documents/Проект/Лоб/Волосы на лбу/l-CXfWtD-6s.jpg",

"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/_6oi_k8GH-0.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/5tZPdunzcJg.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/6GzzI5L36_w.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/91jnqc7uhP8.jpg", 
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/460x598_1_b481c156f3a6fe7e00d0ef57051f3a3f@460x598_0xc0a839a4_6873888541479221755.jpeg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/2008_7.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/-CvOo3gIYBw.jpg", 
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/depositphotos_96932674-stock-photo-guy-with-a-beard-smoking.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/_fDPIybvfaA.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/kL5PZJ4TqzY.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/KZRHwF6CbxU.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/RSucfjHvxKE.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/t8Bvk7cRrAA.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/VX0Fh_Dd4bc.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/wAj_wz2tyu4.jpg",
"/home/vector/Documents/Проект/Лоб/Выпуклый лоб/WCJ9GGhc.jpeg",

"/home/vector/Documents/Проект/Лоб/Квадратный рост волос/00000148.jpg",
"/home/vector/Documents/Проект/Лоб/Квадратный рост волос/Rick_Malambri_00.jpeg",
"/home/vector/Documents/Проект/Лоб/Квадратный рост волос/w5Z3xG6g84M.jpg",
"/home/vector/Documents/Проект/Лоб/Квадратный рост волос/ZbHp5DhkuMw.jpg",

"/home/vector/Documents/Проект/Лоб/Полукруглой рост волос/4EFmDmLPrj8.jpg",
"/home/vector/Documents/Проект/Лоб/Полукруглой рост волос/6wZeJ_uYft4.jpg",
"/home/vector/Documents/Проект/Лоб/Полукруглой рост волос/cnOgcnfEkB8.jpg",
"/home/vector/Documents/Проект/Лоб/Полукруглой рост волос/d5viKpho85c.jpg",
"/home/vector/Documents/Проект/Лоб/Полукруглой рост волос/eiynnlrBp44.jpg",
"/home/vector/Documents/Проект/Лоб/Полукруглой рост волос/PbHfhU1Wl0k.jpg", 
"/home/vector/Documents/Проект/Лоб/Полукруглой рост волос/ZEKo9yadrsQ.jpg", 

"/home/vector/Documents/Проект/Лоб/Прямой лоб/7Rru1xQSzZM.jpg",
"/home/vector/Documents/Проект/Лоб/Прямой лоб/qNZrI-hzJU4.jpg",
"/home/vector/Documents/Проект/Лоб/Прямой лоб/S8sbeN4fBw4.jpg",
"/home/vector/Documents/Проект/Лоб/Прямой лоб/zachasannye_volosy.jpg",

"/home/vector/Documents/Проект/Лоб/Узкий лоб/7ed054c4455a5cab11e77b65f85eaa27cd30fed3.jpg",
"/home/vector/Documents/Проект/Лоб/Узкий лоб/7RKrUm-yR7w.jpg",
"/home/vector/Documents/Проект/Лоб/Узкий лоб/00000148.jpg",
"/home/vector/Documents/Проект/Лоб/Узкий лоб/60789c4f2bb6194debab7eecdbf490be.jpg",
"/home/vector/Documents/Проект/Лоб/Узкий лоб/aIamGxJLLig.jpg",
"/home/vector/Documents/Проект/Лоб/Узкий лоб/d37d6aa62a7c5b701cf9100e58dda2b9.jpg",
"/home/vector/Documents/Проект/Лоб/Узкий лоб/,.jpg",
"/home/vector/Documents/Проект/Лоб/Узкий лоб/miPQdBLa86E.jpg",
"/home/vector/Documents/Проект/Лоб/Узкий лоб/s1200.jpg",

"/home/vector/Documents/Проект/Лоб/Широкий лоб/4EFmDmLPrj8.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/a17d_NXrYB4.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/a807d8b9be4daf73177c624b4c81fb70.jpeg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/C6qy3C7iGI4.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/d37J1AwFy8I.jpg", 
"/home/vector/Documents/Проект/Лоб/Широкий лоб/d37J1AwFy8I.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/oEZnQwXMPv4.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/r7UBuxhfya8.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/rQ5Uav6g3a0.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/selfie-_vb11.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/SKBQ1wXe5wY.jpg",
"/home/vector/Documents/Проект/Лоб/Широкий лоб/V9ntVxnffVE.jpg",

"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/0WsRWPjUgiY.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/1u3SJsknSj0.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/9TS05TH4A1s.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/716Tr7QMsSs.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/BVzriiDtJxM.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/D3AwF--bdk8.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/eSL3tGPB8Fc.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/hpedwgNYDy0.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/LpET9oEtqZ0.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/mL8dyWc3wFA.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/nTQfhO7idaA.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/PpGtU4gI1hA.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/qkywwBvQK8Q.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/rjFfJr1QxC0.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/v9AZ1IBD_70.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/yP9SY4VMoLo.jpg",
"/home/vector/Documents/Проект/Миры/Семейный/Проект/Лоб/Широкий лоб/ZkhBih2dud0.jpg",
"/home/vector/Documents/Проект/Миры/Материальный/ecAZC3qUaYs.jpg",
"/home/vector/Documents/Проект/Миры/Материальный/JbD6OrAJQSI.jpg",
"/home/vector/Documents/Проект/Миры/Материальный/KIEKaAquVks.jpg",
"/home/vector/Documents/Проект/Миры/Материальный/nSiqg88zCUY.jpg",
"/home/vector/Documents/Проект/Миры/Материальный/sQlwhjHt7jQ.jpg",
"/home/vector/Documents/Проект/Миры/Материальный/tlKTZLGm3Uw.jpg",

"/home/vector/Documents/Проект/Миры/Духовный/-2tWawdSC9Y.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/4aGScAcKnsM.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/77FTpghDo_w.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/Bi6IRjLP64g.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/BK3EoRBbNZ4.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/CUDKkCLPBNE.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/cxTmIKDDbTU.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/d37J1AwFy8I.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/ESQ3Cw3aBLo.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/i71BcpPsCaI.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/KeZHmecxL9I.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/lI9gElzyCkc.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/mhGWAGTufp4.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/moKFHbZqD-I.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/wk6Tc3wvG0g.jpg",
"/home/vector/Documents/Проект/Миры/Духовный/yn1sCYJWbiA.jpg",

"/home/vector/Documents/Проект/Нос/Кончик носа вниз/2asGxg2QSBw%20(1).jpg",
"/home/vector/Documents/Проект/Нос/Кончик носа вниз/6sIf3GjQLlE.jpg",
"/home/vector/Documents/Проект/Нос/Кончик носа вниз/gjl4DreMk14.jpg",
"/home/vector/Documents/Проект/Нос/Кончик носа вниз/KcyqKYHtTnk.jpg",
"/home/vector/Documents/Проект/Нос/Кончик носа вниз/qJ8igto1NJI.jpg",
"/home/vector/Documents/Проект/Нос/Кончик носа вниз/yQPwS_gP2Y8.jpg",

"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/1qRq-GQM.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/1YMAZhwY.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/3Pxgt-O4.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/6B-S0zW0.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/26qEuNjg.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/49gn21lU.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/65RS0sS0.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/bD9XvQw8.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/bgvx9u2U%20(1).jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/B-l1uBluYhY.jpg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/cbY0KADo.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/Dr0-NIQE.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/E1bTfBXs.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/EMzOQsiM.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/GwW8rJfBG2c.jpg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/HpdRVvAM.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/jllAMfkrzJ8.jpg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/K71N0KOQ.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/NeEqV_ak.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/NZRZNH1I.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/QXHQTQzuXok.jpg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/R5YYOIMs.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/s7dx9pQ4.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/w1xxgAgY.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/xBrhn6co.jpeg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/YdX2mXn5tfc.jpg",
"/home/vector/Documents/Проект/Нос/Крылья носа очерчены/zlP0bdcajmQ.jpg",

"/home/vector/Documents/Проект/Нос/Курносый нос/24kyu12.jpg",
"/home/vector/Documents/Проект/Нос/Курносый нос/CWkla0jfiOc.jpg",
"/home/vector/Documents/Проект/Нос/Курносый нос/czt4snqob35sjuwn4zqm.jpg",
"/home/vector/Documents/Проект/Нос/Курносый нос/NDBcrKd-qQs.jpg",
"/home/vector/Documents/Проект/Нос/Курносый нос/NU_0lwAK0dg.jpg",
"/home/vector/Documents/Проект/Нос/Курносый нос/q0culp9AeDo.jpg",
"/home/vector/Documents/Проект/Нос/Курносый нос/s1200%20(12).jpg",
"/home/vector/Documents/Проект/Нос/Курносый нос/VWC9rXqR7AE.jpg",
"/home/vector/Documents/Проект/Нос/Курносый нос/yw-8tH3S4jE.jpg",

"/home/vector/Documents/Проект/Нос/Нос картошкой/6tR2SI1NBWE.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/dBA6ipQcoC8.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/DgCOx4s7F-k.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/DSC035312.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/FLji2yt32wg.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/l1tzhfmZvY4.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/lH8vT8ssZak.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/stvwCm2TmIY.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/tyxbUSfV4Zs.jpg",
"/home/vector/Documents/Проект/Нос/Нос картошкой/zi-3LsykPHQ.jpg",

"/home/vector/Documents/Проект/Нос/Нос с горбинкой/2.jpg", 
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/597c2f0769b881ec318f944fb4a20996_fitted_740x700.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/1055027895.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/2207654447.jpg", 
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/Amatue_piercing.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/Bf14wtqnJ7A.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/B-tfiD9MLAU.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/cSABJdvVDf4.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/HgKouXqSEec.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/nOBR4pv3GQ0.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/oGnJFqM5vn8.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/oRLSQ-Kp1t0.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/sqpIl9VyJ7s.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/v3U4aSrRGB0.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/_XSzgbjqOxY.jpg",
"/home/vector/Documents/Проект/Нос/Нос с горбинкой/z_c6e26831.jpg",

"/home/vector/Documents/Проект/Нос/Переносица с впадиной/1VqKI1Fg.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/2GIeUVIQ.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/2ue9gO1o.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/a_HIWnGx0jw.jpg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/dNgvfDS-UxM.jpg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/HTtmqqYMk08%20(1).jpg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/J87mu4dloXg.jpg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/n9KHRD4A.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/oiyybptA.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/PQO7noBw.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/q9JRFld4GQs.jpg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/RKeti1DsILU.jpg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/rxvsVylY.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/TFBRB5bY.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/Uc9PaAUQ.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/w_LakXKgY3s.jpg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/WN5Vzu9w.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/Y1jqnVho.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/Yrv03a-8.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/yTYTUHxs.jpeg",
"/home/vector/Documents/Проект/Нос/Переносица с впадиной/zTW4p5Mo.jpeg",

"/home/vector/Documents/Проект/Нос/Прямой нос/0si5h1EQqgY.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/2ElQXASifwQ.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/eiynnlrBp44.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/_k6HVAugsas.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/oOgL8cyeyHM.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/OOtrsaVpVDE.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/Ox5NcFei7c0.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/P0NA6ryIIwU.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/VZHbSR5Lh10.jpg",
"/home/vector/Documents/Проект/Нос/Прямой нос/z_9e260f25.jpg",


"/home/vector/Documents/Проект/Подбородок/Квадратный/7JfUU-BHhI4.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/AE71s4EuSko.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/D_eJdyfI8sw.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/D_eJdyfI8sw.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/LiFX9d95ZEc.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/qHzTMJJa_q4.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/TKF3IEDuwKo.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/vNiMFEurK6U.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/WHjmI_OtFRM.jpg",  
"/home/vector/Documents/Проект/Подбородок/Квадратный/XlseKAagjeA.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/XNXxhTIjau4.jpg",
"/home/vector/Documents/Проект/Подбородок/Квадратный/Y4saBdVyhwk.jpg",  

"/home/vector/Documents/Проект/Подбородок/Круглый/0WsRWPjUgiY.jpg",
"/home/vector/Documents/Проект/Подбородок/Круглый/8i4shwUT7do.jpg",
"/home/vector/Documents/Проект/Подбородок/Круглый/b5G5usvFinY.jpg",
"/home/vector/Documents/Проект/Подбородок/Круглый/mpr30ZLERew.jpg",
"/home/vector/Documents/Проект/Подбородок/Круглый/V_Ie4ZTC4OQ.jpg",
"/home/vector/Documents/Проект/Подбородок/Круглый/WheRLObn9Wg.jpg",

"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/6GzzI5L36_w.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/cG1GZOE2odc.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/DpqSK751ic8.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/dREz0aff6yk.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/EibHtICOFdI.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/faoNNEuf7iY.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/gjl4DreMk14.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/gyGQ86UVusc.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/mB6uBqpvSsI.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/oIXKSs5_gGg.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/OYi6rI-Yqws.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/SjhoSAfQzhk.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/tAnbhTeBcJE.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/wRJ5kYcL7W4.jpg",
"/home/vector/Documents/Проект/Подбородок/Маленький подбородок/zoeUy8BJ5rc.jpg",

"/home/vector/Documents/Проект/Подбородок/Раздвоенный с вмятиной/AWlw0G-QWDk.jpg",
"/home/vector/Documents/Проект/Подбородок/Раздвоенный с вмятиной/be3af9f5ff3072886ca9cbac27acf3f7.jpg",
"/home/vector/Documents/Проект/Подбородок/Раздвоенный с вмятиной/eHfGvFR9ZKs.jpg",
"/home/vector/Documents/Проект/Подбородок/Раздвоенный с вмятиной/middle_4fe9990855f94.jpeg",

"/home/vector/Documents/Проект/Скулы/Скулы выше уровня глаз/6iy_t-CYI4k.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы выше уровня глаз/iKR7ziCKzyQ.jpg",

"/home/vector/Documents/Проект/Скулы/Скулы на уровне глаз/6hClGhd0v2k.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы на уровне глаз/690x1035_1_c19b97d0e8ff3c343746dc1a7358094a-1159x1739_0xd42ee42a_4267633891394268146.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы на уровне глаз/_BiWdt-QiwY.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы на уровне глаз/LpET9oEtqZ0.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы на уровне глаз/MUIgjwzSGv4.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы на уровне глаз/sR9h_tZ_N5E.jpg",

"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/_54ZB-4PU.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/_54ZB-n9B54PU.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/1CtulCZRNdc.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/2nkoVQCdWeo.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/7gULiCG2q8s.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/9TS05TH4A1s.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/26WrSfBsFMM.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/EYzmdCAFJMA.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/L5WRL9xqdh0.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/O3en1tdgpP0.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/PD2GiyjSvlk.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/s12050.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/vU3GWg8atic.jpg",
"/home/vector/Documents/Проект/Скулы/Скулы ниже уровня глаз/YJHleP-BATM.jpg",

"/home/vector/Documents/Проект/Уши/Большая мочка уха/-2vl_tnQdCk.jpg", 
"/home/vector/Documents/Проект/Уши/Большая мочка уха/1LZhkqAkLCA.jpg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/2Smsf7uZmvY.jpg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/9VITkamMdsY.jpg",

"/home/vector/Documents/Проект/Уши/Большая мочка уха/460x598_1_b481c156f3a6fe7e00d0ef57051f3a3f@460x598_0xc0a839a4_6873888541479221755.jpeg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/dvaC6cfJ6SA.jpg",  
"/home/vector/Documents/Проект/Уши/Большая мочка уха/h6v4NCLQkqc.jpg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/lR_JG9UisH8.jpg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/lVG13lHw.jpeg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/mRQwgw411C0.jpg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/OvmLUZziFyY.jpg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/s5azrJxA.jpeg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/u2s0PdoQ.jpeg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/wZ7kKmWQ.jpeg",
"/home/vector/Documents/Проект/Уши/Большая мочка уха/ZXqK2_2w.jpeg",

"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/5tEDFVNwyKU.jpg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/97d4O_UCIrA.jpg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/c6XPV0qBG3Q.jpg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/d8RaFh-w.jpeg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/DT8_Yo5I.jpeg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/Fwb7BEuakio.jpg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/Gh4CoCRDQlQ.jpg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/hKfgiNvM.jpeg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/hQBfaEjo.jpeg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/mota.ru_2016110454.jpg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/NJZeFVNp51s.jpg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/TbANvOQGO6Y.jpg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/VEm9DCRQ.jpeg",
"/home/vector/Documents/Проект/Уши/Квадратная мочка уха/w9fw-SJO9AY.jpg",

"/home/vector/Documents/Проект/Уши/Лопоухие уши/4GOrhORb188.jpg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/5HFuu-Sw.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/410x600_1_c57ca17252c7d71feb9c4769b1983c07@410x600_0xd42ee437_5621963761436870209.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/aaUUsO4w.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/cq9fu97Q.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/dioLSFpQ.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/GFArgsSQ.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/girls-haircuts-2015-fades-unique-biracial-mens-hairstyles-of-girls-haircuts-2015-fades.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/iAwichjQ.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/KAF4N80DF_g.jpg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/Klzir_ynlYc.jpg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/My0S1iAEewU.jpg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/nRjswudA.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/post_5b75286304047.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/QgHZM6UA.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/qw5RGwgA.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/qY5yklCw.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/RHdBnCew.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/ThgqM3nA.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/tom-ford-brown-round-frame-tortoiseshell-acetate-optical-glasses-product-5-866757520-normal.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/Ur8vWP8A.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/wR042hiQ.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/X3vzxQzw.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/ZOjo9CHg.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/ZPfph2JQ.jpeg",
"/home/vector/Documents/Проект/Уши/Лопоухие уши/Zwf7sE4Q.jpeg",

"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/fmXhnBkN2AI.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/_g6LH7-fsbU.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/GpS2oG3k.jpeg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/hxRc39KPq2A.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/ifDoum-U.jpeg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/j5-jr5reR1k.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/jd1TAOYUisA.jpg",  
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/jY5tQdkNKt4.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/Mb3dX-_9uxM.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/N3Dr9Zxg.jpeg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/rSoRiJDVygc.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/rWPlY_7_fas.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/SQrbZlPZs_A.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/ttwg30scCiI.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/UqwUWYes.jpeg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/ViPoDOFwV2s.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/wcQgB7OrDBg.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/Wd5bme9YlYg.jpg", 
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/x7lB9a8iBYg.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/YMSq2ny_EYc.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/YRmvaWqE0_w.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/Y-xLFV8ep0A.jpg",
"/home/vector/Documents/Проект/Уши/Маленькая мочка уха/7XoSKn3BxMU.jpg",

"/home/vector/Documents/Проект/Уши/прижатые Уши/2Nv7vct4bHE.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/4zPdSU4hskM.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/0647be740506c6db12b4093564a2cc6c.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/FghhuZDoQEY.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/I-7jK2Pw.jpeg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/iYOYY5KFVtw.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/ncxLltmCVEY.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/oaxzdq1J69Y.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/tuJMYfpddM4.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/z5U14aDKvaw.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/YoiCvFc3oC8.jpg",
"/home/vector/Documents/Проект/Уши/прижатые Уши/%D0%B2%D0%B20.jpeg",

"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/5CmmTX9g.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/6YpbZcSQ.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/AqaM61RQ.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/BawlpqbNYvM.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/depositphotos_171911278-stock-photo-woman-in-white-blouse.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/depositphotos_200804876-stock-photo-close-portrait-pensive-african-american.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/eLBaFMcpwRE.jpg",  
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/flEYUHck.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/gM4hSZUQ.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/ibO5jh7Q.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/iqmm8TzE.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/k1LbORh1I_U.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/LJZglgLsc9I.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/lRTYgwnA.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/LyH87oi9FUI.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/natalie_portman_brunette_face_profile_makeup_29043_1920x1080.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/nQ2WbIrg.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/sys3qo7nGP4.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/T6kLeCTA.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/TJIEqKTA.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/TKsGz6ZA.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/VfLL7rAA.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/VNm6TDEg.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/_w5JUGHF8hE.jpg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/xzsGzibQ.jpeg",
"/home/vector/Documents/Проект/Уши/Приросшая мочка уха/ZtdRfUAQ.jpeg",

"/home/vector/Documents/Проект/Форма лица/Вода/4udgAKXf5Tw.jpg",
"/home/vector/Documents/Проект/Форма лица/Вода/J8henH8wRAQ.jpg",
"/home/vector/Documents/Проект/Форма лица/Вода/MywyF5Ccfyk.jpg",
"/home/vector/Documents/Проект/Форма лица/Вода/mzUn_66y8bE.jpg",
"/home/vector/Documents/Проект/Форма лица/Вода/qAllvNocw2c.jpg",
"/home/vector/Documents/Проект/Форма лица/Вода/rouXsSgd_RY.jpg",
"/home/vector/Documents/Проект/Форма лица/Вода/XGNR1dmgjwU.jpg",
"/home/vector/Documents/Проект/Форма лица/Вода/xRLBqAT4VnA.jpg",
"/home/vector/Documents/Проект/Форма лица/Вода/YPg2cmRiRdM.jpg",

"/home/vector/Documents/Проект/Форма лица/Воздух/0ZN2t5dntmE.jpg",
"/home/vector/Documents/Проект/Форма лица/Воздух/2e7b7807d523c72088c90459fefda244.jpg",
"/home/vector/Documents/Проект/Форма лица/Воздух/1425582662_1.jpeg",
"/home/vector/Documents/Проект/Форма лица/Воздух/-m-Uc6zH_V4.jpg",
"/home/vector/Documents/Проект/Форма лица/Воздух/rhnHnHXweKA.jpg",
"/home/vector/Documents/Проект/Форма лица/Воздух/YzDF-M5wqC0.jpg",
"/home/vector/Documents/Проект/Форма лица/Воздух/ZQLi7eaVZhs.jpg",

"/home/vector/Documents/Проект/Форма лица/Огонь/3aGo2khqz1pp1W5E6NV3n3ZX846LDz.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/7a29d9430ca87823cc480e6b192c8bd100fc467dr2-736-736v2_00.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/d022f2a0345acd6e9f25248776efe8f097363fa9r2-480-480v2_00.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/depositphotos_143414137-stock-photo-little-kid-girl-looking-happy.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/devushka-lico-shturmovaya-5687.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/G1rehvNDSew.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/original.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/sC3q4Scfkbo.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/SSUR-COMME-DES-FUCKDOWN-Beanie-Hat-For-Men-Knitted-Wool-Winter-Cap-Women-Baseball-Cap-Adults.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/Y4heFvFC32k.jpg",
"/home/vector/Documents/Проект/Форма лица/Огонь/zDRnRJk7hoU.jpg"
}

for i in dlib_errors:
    print(i)